server.port=9080
spring.jpa.hibernate.ddl-auto=none

# Liquibase configuration for test profile
spring.liquibase.change-log=classpath:db/changelogs/db.changelog-master.xml
spring.liquibase.enabled=true

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.enabled=false
