server.port=9080

# datebase configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.hibernate.ddl-auto=none

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelogs/db.changelog-master.xml
spring.liquibase.enabled=true

